### ISSUE TITLE
OpenSSL 3.2

### ISSUE THREAD

**Issue by malytomas** [yhirose/cpp-httplib#1790]
I get build error with openssl 3.2.1

```
httplibd.lib(httplib.obj) : error LNK2019: unresolved external symbol SSL_get1_peer_certificate referenced in function "public: __cdecl `private: bool __cdecl httplib::SSLClient::initialize_ssl(struct httplib::ClientImpl::Socket &,enum httplib::Error &)'::`2'::<lambda_1>::operator()(struct ssl_st *)const " (??R<lambda_1>@?1??initialize_ssl@SSLClient@httplib@@AEAA_NAEAUSocket@ClientImpl@3@AEAW4Error@3@@Z@QEBA@PEAUssl_st@@@Z)
```

On windows. Using latest httplib 6791a8364d1644b44e0fb13fca472c398f78eb67. Same code builds ok with openssl 3.1.1.

**Comment by yhirose** [comment]
@malytomas thanks for the report, if it's a link error and you can at least compile the code, could you make sure you link an appropriate lib file provided by openssl?

**Comment by malytomas** [comment]
I got this error when building project on github actions. The installed version of openssl was the only difference.
I am using Chocolatey for the installation.

```yml
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install OpenSSL
      run: |
        choco install openssl -y --version=3.1.1
```

Version 3.2.1 was the default when I provided no explicit version.

**Comment by yhirose** [comment]
> I got this error when building project on github actions.

If so, this problem has nothing to do with cpp-httplib itself, but a problem in the Chocolatey. Could you send an issue to them instead? Thanks!
