### ISSUE TITLE
Cannot compile with MinGW G++ 9.2.0

### ISSUE THREAD

**Issue by Untitled** [yhirose/cpp-httplib#529]
Sorry but it seems not compatible with some of the compilers.
[Log](https://paste.ubuntu.com/p/23KS88Ms8Z/)
I've tried to build it with my whole project but it gave me errors above.
It seems the same when building splited httplib.cc alone.
MinGW G++ 9.2.0,Windows 10
The errors is meaningless,for example
``
httplib.h:201:1: note: 'std::thread' is defined in header '<thread>'; did you forget to '#include <thread>'?
  200 | #include <thread>
  +++ |+#include <thread>
  201 |
``
Can you help me with that?This is really a great library but I have no luck using it :(
Thanks!

**Comment by Untitled** [comment]
Thanks!
With TDM-GCC it bypassed the thread errors but there's still some errors left :(
It is a common problem about `ws2tcpip.h`
[StackOverflow](https://stackoverflow.com/questions/20303583/socket-programming-in-mingw)
Likely, I got errors,'getaddrinfo' was not declared in this scope.
Some of this can be solved by adding`#define _WIN32_WINNT  0x501`, 
but not working for me - My 'getaddrinfo' declaration is at pthread.h ,not like those who have
```#if (_WIN32_WINNT >= 0x0501)
void WSAAPI freeaddrinfo (struct addrinfo*);
int WSAAPI getaddrinfo (const char*,const char*,const struct addrinfo*,
                struct addrinfo**);
int WSAAPI getnameinfo(const struct sockaddr*,socklen_t,char*,DWORD,
               char*,DWORD,int);
#else
/* FIXME: Need WS protocol-independent API helpers.  */
#endif```
This is not fault of CppHttplib but the compiler since it worked well in MSVC compiler
I'm going working on these errors and recently it seemed not compatible with mingw or tdm-gcc.
Thanks so much!

**Comment by PixlRainbow** [comment]
its probably because MSVC compiler will auto-link and auto-include some Windows API components by default where MinGW G++ will not, while G++ on Linux/Mac does not have this issue because the POSIX API is accessible.

**Comment by yhirose** [comment]
I think I can close it, right? Thanks for all the comments!
