### ISSUE TITLE
expression cannot be used as a function

### ISSUE THREAD

**Issue by snagar** [yhirose/cpp-httplib#577]
Hi,
When I try to compile your cpp-httplib against OpenSSL v1.1.1 I receive the following error. I'm not sure what I'm missing but I'll appreciate your insight.

I compile in Linux Mint Mate 19.3.
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Main error**
> /home/xplane/programming/git/missionx_v3_git/libs/cpp-httplib/httplib.cc: In lambda function:
> /home/xplane/programming/git/missionx_v3_git/libs/cpp-httplib/httplib.cc:4311:58: error: expression cannot be used as a function
>            auto server_cert = SSL_get_peer_certificate(ssl);
>                                                           ^
> 

**The full command + errors are:**
> g++ -std=c++14 -D_UNICODE -DLIN=1 -DMB_DOUBLE_FLOAT -DXPLM200 -DXPLM210 -DXPLM300 -DMX_GL -DDEBUG -DXPLM301 -DENABLE_FREETYPE_ -Dglm_shared_EXPORTS -DFT2_BUILD_LIBRARY -DXPLM302 -DXPLM_DEPRECATED -DIMGUI_INCLUDE_IMCONFIG_H=1 -DIMGUI_IMPL_OPENGL_LOADER_GLEW=1 -DCPPHTTPLIB_OPENSSL_SUPPORT=1 -DSSL_get_peer_certificate=1 -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/SDK/CHeaders/XPLM" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/SDK/CHeaders/Widgets" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/SDK/CHeaders/Wrappers" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/fmod/inc" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/imgui4xp" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/imgui4xp/imgui" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/imgui4xp/KHR" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/imgui4xp/imgui/example" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/imgui4xp/imgWindow" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/sqlite/sqlite" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../src/ui/core/brotli/include" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/gl/linux/inc" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/cpp-httplib" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../src/ui/core/freetype/include" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../src/ui/core" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/stb" -I"/home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/OpenSSL/openssl-111/include" -O0 -g3 -p -pg -Wall -c -fmessage-length=0 -fexceptions -fpermissive  -Wunused-function -fPIC -MMD -MP -MF"libs/cpp-httplib/httplib.d" -MT"libs/cpp-httplib/httplib.o" -o "libs/cpp-httplib/httplib.o" "/home/xplane/programming/git/missionx_v3_git/libs/cpp-httplib/httplib.cc"
> <command-line>:0:26: error: expected unqualified-id before numeric constant
> /home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/OpenSSL/openssl-111/include/openssl/ssl.h:1678:14: note: in expansion of macro ‘SSL_get_peer_certificate’
>  __owur X509 *SSL_get_peer_certificate(const SSL *s);
>               ^~~~~~~~~~~~~~~~~~~~~~~~
> <command-line>:0:26: error: expected initializer before numeric constant
> /home/xplane/programming/git/missionx_v3_git/eclipse/missionx/../../libs/OpenSSL/openssl-111/include/openssl/ssl.h:1678:14: note: in expansion of macro ‘SSL_get_peer_certificate’
>  __owur X509 *SSL_get_peer_certificate(const SSL *s);
>               ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/xplane/programming/git/missionx_v3_git/libs/cpp-httplib/httplib.cc: In lambda function:
> /home/xplane/programming/git/missionx_v3_git/libs/cpp-httplib/httplib.cc:4311:58: error: expression cannot be used as a function
>            auto server_cert = SSL_get_peer_certificate(ssl);
>                                                           ^
> make: *** [libs/cpp-httplib/httplib.o] Error 1
> libs/cpp-httplib/subdir.mk:18: recipe for target 'libs/cpp-httplib/httplib.o' failed
> "make all" terminated with exit code 2. Build might be incomplete.

**Comment by yhirose** [comment]
It seems like `-DSSL_get_peer_certificate=1` causes the problem. Hope it helps.

**Comment by snagar** [comment]
Hi,

Embarrassing as it is, I forgot to clean some of the settings I did so yes you are 100% correct.
By the way, 

1. Does your library support or will OpenSSL3x or you are waiting for it to reach Release phase.
2. Does your library supports OSX too ?

Thanks

**Comment by yhirose** [comment]
> Does your library support or will OpenSSL3x or you are waiting for it to reach Release phase.
Since it's still Alpha version, I am not interested in it yet.

> Does your library supports OSX too ?
Yes, I am mainly working on macOS.
