### ISSUE TITLE
OpenSSL invalid conversion from ‘void*’ to ‘const stack_st_GENERAL_NAME*’

### ISSUE THREAD

**Issue by PixlRainbow** [yhirose/cpp-httplib#153]
compiling a server with `CPPHTTPLIB_OPENSSL_SUPPORT` enabled and the following command
```g++ -std=c++11 server.cpp -o server -pthread -lssl -lcrypto```
causes the following error
```
In file included from server.cpp:5:0:
/usr/include/httplib.h: In member function ‘bool httplib::SSLClient::verify_host_with_subject_alt_name(X509*) const’:
/usr/include/httplib.h:2481:47: error: invalid conversion from ‘void*’ to ‘const stack_st_GENERAL_NAME*’ [-fpermissive]
     auto count = sk_GENERAL_NAME_num(alt_names);
                                               ^
```
I have `libssl-dev:amd64 1.1.0g-2ubuntu4.3` installed
My full code is attached below. I had to rename it to .txt for github to accept it, but you can rename it back to .cpp
**[server.txt](https://github.com/yhirose/cpp-httplib/files/3219502/server.txt)**
Forcing a compile with `-fpermissive` produces an executable that immediately returns after a call to `svr.listen` without errors.

Visual Studio Code also detects the following errors in `httplib.h`
![image](https://user-images.githubusercontent.com/44422178/58372034-4d23a580-7f4a-11e9-98ee-f6c2655151f6.png)

**Comment by PixlRainbow** [comment]
nevermind, downgraded to libssl1.0-dev and it now compiles without errors and works fine

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the report. The code now can compile with openssl 1.1. #155.
