### ISSUE TITLE
httplib won't compile with GCC-12 on Windows unless <cstring> is included

### ISSUE THREAD

**Issue by mcordova1967** [yhirose/cpp-httplib#1281]
I have compiled httplib with GCC-12 on Linux without problem, also with GCC-11.3 on Windows, but when compiling with GCC-12 on Windows (using MSYS2 package) the compiler prints this error:

../src/httplib.h: In constructor 'httplib::detail::gzip_decompressor::gzip_decompressor()':
../src/httplib.h:3064:8: error: 'memset' is not a member of 'std'; did you mean 'wmemset'?
 3064 |   std::memset(&strm_, 0, sizeof(strm_));
      |        ^~~~~~
      |        wmemset

<cstring> must be included inside one of the #ifdef _WIN32 blocks in order to compile.
As I mentioned, it was compiling OK with GCC-11.3 despite not having this <cstring> header, but GCC-12 complains.
To be honest, it's more of a mystery to me why it was compiling with GCC-11.3 on Windows, it should fail because std::memset requires <cstring> and it is being included only if Linux.

**Comment by yhirose** [comment]
@mcordova1967, could you please send me a pull request, since I don't use MSYS2. Thanks!

**Comment by mcordova1967** [comment]
I am sorry, I have never done a pull request before, should I fork the project first? I will read GitHub tutorials and try to do it.

It's just about adding an include for Windows too:
`

#include <cstring>

`
In the current version, it is only being included if not Win32. 
Somehow it did compile with GCC 11.3 without problem, but GCC-12 complains about it.

Regards.

**Comment by yhirose** [comment]
> I am sorry, I have never done a pull request before, should I fork the project first? I will read GitHub tutorials and try to do it.

You can check [this article](https://opensource.com/article/19/7/create-pull-request-github) to see what to do. It's not difficult at all.

The reason why I asked you to send a pull request is that I can't verify the change on my machine since I don't have the MSYS environment. Also if you push your pull request, the GitHub Actions workflow will run all the unit test cases on Linux/Windows/macOS. And finally, it's very easy for me to do code review.

Thanks for your understanding!
