### ISSUE TITLE
C++14 required?

### ISSUE THREAD

**Issue by TTimo** [yhirose/cpp-httplib#1585]
Hello,

I'm getting this error with gcc 13.1.1:

```
cpp-httplib/httplib.h:5252:21: error: lambda capture initializers only available with ‘-std=c++14’ or ‘-std=gnu++14’ [-Werror=c++14-extensions]
 5252 |   error_handler_ = [handler = std::move(handler)](const Request &req, Response &res) {
      |                     ^~~~~~~
```

The documentation advertises C++11, is this a configuration problem, or an oversight, or maybe is C++14 actually needed? I can probably enable C++14 support in the build system, but it's a patch for an upstream developer so if possible I'd rather not.

**Comment by yhirose** [comment]
@TTimo It's a bug, cpp-httplib should be C++11 compatible. This is caused by https://github.com/yhirose/cpp-httplib/commit/698a1e51ecc6450b19757169736b173730c1d440, and I have actually fixed it at https://github.com/yhirose/cpp-httplib/commit/ed129f057fe0c1f035681c18907b1a27c5a08df8.

The official release versions such as v12.0.5 and v12.0.6 are fine with C+11. Thanks for the report!
